wellyshen/react-cool-virtual

- .changeset/sour-badgers-glow.md
- src/useVirtual.ts
- Fix(useVirtual): correct the `start` value of `items`
> Fix(useVirtual): correct the `start` value of `items`

- .changeset/hip-olives-give.md
- src/useVirtual.ts
- Fix(useVirtual): fix the randomly grid cells when working with dynamic size
> Fix(useVirtual): fix the randomly grid cells when working with dynamic size

- .changeset/bright-geckos-eat.md
- README.md
- src/useVirtual.ts
- Fix(useVirtual): real-time dynamic size not working
> Fix(useVirtual): real-time dynamic size not working

- .changeset/six-rabbits-sort.md
- src/useVirtual.ts
- perf: performance improvement for real-time resize
> perf: performance improvement for real-time resize

- .changeset/angry-ligers-wink.md
- src/useVirtual.ts
- Perf: performance optimizing for rendering huge datasets  (e.g. grid)
> Perf: performance optimizing for rendering huge datasets (e.g. grid)

- .changeset/small-frogs-leave.md
- src/types/index.ts
- src/types/react-cool-virtual.d.ts
- src/useVirtual.ts
- src/utils/useResizeEffect.ts
- Feat: new `onResize` event callback
> Feat: new `onResize` event callback

- .changeset/tough-dogs-arrive.md
- app/src/App/index.tsx
- app/src/App/styles.module.scss
- src/useVirtual.ts
- perf: improvement the performance of calculating scroll offset
> perf: improvement the performance of calculating scroll offset

- .changeset/cool-worms-marry.md
- src/useVirtual.ts
- fix: scroll position behavior
> fix: scroll position behavior

- .changeset/tough-snails-sniff.md
- app/src/App/index.tsx
- app/src/App/styles.module.scss
- src/useVirtual.ts
- perf: performance improvement
> perf: performance improvement

- .changeset/small-donuts-push.md
- app/src/App/index.tsx
- src/types/index.ts
- src/types/react-cool-virtual.d.ts
- src/useVirtual.ts
- Feat: support enable/disable the `isScrolling` property by the speed of scrolling
> Feat: support enable/disable the `isScrolling` property by the speed of scrolling

- .changeset/eighty-terms-repeat.md
- app/package.json
- app/src/App/index.tsx
- app/yarn.lock
- src/useVirtual.ts
- Fix: `loadMore` callback not working
> Fix: `loadMore` callback not working

- .changeset/silent-trains-applaud.md
- src/useVirtual.ts
- Fix: infinite scroll causes dynamic size item jumping
> Fix: infinite scroll causes dynamic size item jumping

- .changeset/fresh-lamps-study.md
- src/useVirtual.ts
> Fix: RWD not working

- .changeset/fluffy-toys-pretend.md
- app/src/App/index.tsx
- app/src/App/styles.module.scss
- src/useVirtual.ts
- Fix: resize-observer broken on Safari
> Fix: resize-observer broken on Safari

- .changeset/little-dancers-vanish.md
- src/useVirtual.ts
- Fix: `isScrolling` flash bug
> Fix: `isScrolling` flash bug

- .changeset/kind-snails-collect.md
- src/useVirtual.ts
- Fix: real-time resize jumping
> Fix: real-time resize jumping

- .changeset/strange-poems-arrive.md
- src/useVirtual.ts
- Perf: cache measurements for better performance
> Perf: cache measurements for better performance

- .changeset/tall-lamps-fix.md
- src/types/index.ts
- src/types/react-cool-virtual.d.ts
- src/useVirtual.ts
- Refactor: remove `keyExtractor` option
> Refactor: remove `keyExtractor` option

- .changeset/five-kids-punch.md
- README.md
- src/types/index.ts
- src/useVirtual.ts
- Refactor: export item size for SSR items
> Refactor: export item size for SSR items

- .changeset/quiet-poems-begin.md
- src/types/index.ts
- src/types/react-cool-virtual.d.ts
- src/useVirtual.ts
- Refactor: rename `loadMoreThreshold` option to `loadMoreCount`
> Refactor: rename `loadMoreThreshold` option to `loadMoreCount`

- .changeset/young-waves-approve.md
- src/useVirtual.ts
- Fix: fallback tp default item size for SSR items
> Fix: fallback tp default item size for SSR items

- .changeset/chilled-moons-visit.md
- src/useVirtual.ts
- Perf: slightly performance improvement
> Perf: slightly performance improvement

- .changeset/tricky-cameras-flow.md
- README.md
- src/useVirtual.ts
- fix: dynamic size not working properly when working with RWD
> fix: dynamic size not working properly when working with RWD

- .changeset/fair-otters-unite.md
- src/useVirtual.ts
Reverts wellyshen/react-cool-virtual#109
> Revert "fix: only triggers `onResize` event when width or height changes"

- .changeset/slimy-llamas-wash.md
- src/useVirtual.ts
- fix: the side-effect of triggering `scrollTo` method
> fix: the side-effect of triggering `scrollTo` method

- .changeset/twelve-eggs-bow.md
- src/useVirtual.ts
- fix: items not updated when `itemCount` changed
> fix: items not updated when `itemCount` changed

- .changeset/olive-news-hang.md
- src/useVirtual.ts
- fix: app crash when working with lazily loading
> fix: app crash when working with lazily loading

- .changeset/rich-waves-prove.md
- src/useVirtual.ts
- fix: dynamic size scroll jumping
> fix: dynamic size scroll jumping

- .changeset/funny-mice-fix.md
- README.md
- src/types/index.ts
- src/types/react-cool-virtual.d.ts
- src/utils/shouldUpdate.test.ts
- fix(types): correct the type of `isScrolling` property
> fix(types): correct the type of `isScrolling` property

- .changeset/dry-buckets-crash.md
- README.md
- src/useVirtual.ts
- fix: `scrollToItem` method freezes scrolling
> fix: `scrollToItem` method freezes scrolling

- .changeset/plenty-papayas-press.md
- README.md
- src/types/index.ts
- src/types/react-cool-virtual.d.ts
- src/useVirtual.ts
- src/utils/easeInOutCubic.test.ts
- src/utils/easeInOutCubic.ts
- src/utils/index.ts
- feat: provides a callback with given `distance` parameter for `scrollDuration` option
> feat: provides a callback with given `distance` parameter for `scrollDuration` option

- .changeset/strange-readers-care.md
- src/__tests__/useVirtual.tsx
- src/useVirtual.ts
- fix: `scrollToItem` width dynamic size causes infinitely loop (#176)
> Fix: `scrollToItem` width dynamic size causes infinitely loop

- .changeset/itchy-dogs-leave.md
- README.md
- src/types/react-cool-virtual.d.ts
- src/useVirtual.ts
- refactor: simplify generic type setup
> Refactor: simplify generic type setup

- .changeset/mighty-coins-matter.md
- src/useVirtual.ts
- fix: app crashes when scrolling with drag bar (#224)
> Fix: app crashes when scrolling with drag bar

- .changeset/chatty-melons-clean.md
- src/useVirtual.ts
- fix: app crash due to filtering (from more to less) ( #244 )
> Fix: app crash due to filtering (from more to less)

- .changeset/shy-mirrors-sin.md
- src/__tests__/useVirtual.tsx
- src/useVirtual.ts
- Fix: filter items not updated correctly ( #248 )
> Fix: filter items not updated correctly

- src/useVirtual.ts
Bug
If we don't know how many items will be in list we should be able to pass dynamic `isItemLoaded` function to be able to check is item loaded or not. 
We should take latest version of passing isItemLoaded function.
Have you done all of these things?
- [N/A] [Documentation](https://github.com/wellyshen/react-cool-virtual/blob/master/README.md) added
- [N/A] TypeScript definitions updated
- [N/A] [Add a changeset](https://github.com/atlassian/changesets/blob/master/docs/adding-a-changeset.md)
> fix: unable to pass dynamic isItemLoaded function

- .changeset/fresh-weeks-lay.md
- README.md
- src/__tests__/useVirtual.tsx
- src/types/index.ts
- src/types/react-cool-virtual.d.ts
- src/useVirtual.ts
- Feat: add `startItemIndex` method for [pre-pending items](https://github.com/wellyshen/react-cool-virtual#pre-pending-items) (#361)
> Feat: add `startItemIndex` method for pre-pending items
