wellyshen/react-cool-virtual

.changeset/warm-waves-brake.md
app/src/App/index.tsx
app/src/App/styles.module.scss
src/types/index.ts
src/types/react-cool-virtual.d.ts
src/useVirtual.ts

- Fix: `scrollToItem` method not working with dynamic size

Fix: `scrollToItem` method not working with dynamic size

---

.changeset/spicy-baboons-wonder.md
src/useVirtual.ts

- Perf: improve the performance of using `scrollToItem` method with non-dynamic-size items

Perf: improve the performance of using `scrollToItem` method with non-dynamic-size items

---

.changeset/witty-boxes-mate.md
src/useVirtual.ts

- Fix: dynamic size scroll jumping

Fix: dynamic size scroll jumping

---

.changeset/stale-glasses-wonder.md
src/useVirtual.ts

- fix: the callback of `scrollToItem` is called twice

fix: the callback of `scrollToItem` is called twice

---

.changeset/grumpy-fans-approve.md
src/useVirtual.ts

- fix: pass correct args to `scrollToItem` method

fix: pass correct args to `scrollToItem` method

---

.changeset/chilly-plums-thank.md
src/useVirtual.ts

- fix: wrong the scroll position of `scrollToItem` when working with dynamic size

fix: wrong the scroll position of `scrollToItem` when working with dynamic size

---

.changeset/angry-moons-pump.md
src/useVirtual.ts

- fix: the callback of `scrollTo` not called when scroll to the same position

fix: the callback of `scrollTo` not called when scroll to the same position

---

.changeset/rich-bats-sin.md
README.md
src/useVirtual.ts

- fix: `scrollToItem` causes empty items when working with dynamic size

fix: `scrollToItem` causes empty items when working with dynamic size

---

.changeset/forty-readers-unite.md
src/types/index.ts
src/types/react-cool-virtual.d.ts

- refactor(types): use `RefCallback` as the type of `measureRef`

refactor(types): use `RefCallback` as the type of `measureRef`

---

.changeset/fair-otters-unite.md
src/useVirtual.ts

- fix: only triggers `onResize` event when width or height changes

fix: only triggers `onResize` event when width or height changes

---

.changeset/moody-bugs-carry.md
src/useVirtual.ts

- refactor: destroy previous resize observer from its callback

refactor: destroy previous resize observer from its callback

---

.changeset/stupid-coins-draw.md
src/useVirtual.ts

- fix: wrong item range when `overscanCount` option set to zero

fix: wrong item range when `overscanCount` option set to zero

---

.changeset/itchy-cups-fail.md
src/useVirtual.ts

- fix: re-calculate items when the size of outer element changes

fix: re-calculate items when the size of outer element changes

---

.changeset/great-lemons-whisper.md
README.md
app/src/App/index.tsx
app/src/App/styles.module.scss
src/types/index.ts
src/types/react-cool-virtual.d.ts
src/useVirtual.ts
src/utils/findNearestBinarySearch.ts

feat: support sticky items

---

.changeset/pretty-maps-exercise.md
src/useVirtual.ts

- fix: `scrollToItem` method causes empty rows

fix: `scrollToItem` method causes empty rows

---

.changeset/nine-bananas-pay.md
src/useVirtual.ts

- fix: `scrollToItem` with center alignment causes infinite loop

fix: `scrollToItem` with center alignment causes infinite loop

---

.changeset/dry-dryers-burn.md
README.md
app/src/App/index.tsx
bundlesize.config.json
src/types/index.ts
src/types/react-cool-virtual.d.ts
src/useVirtual.ts

- Feat: add `resetScroll` option for you to handle filtering/sorting without hassle (#150)

Feat: add `resetScroll` option for you to handle filtering/sorting without hassle

---

.changeset/gorgeous-avocados-develop.md
app/src/App/index.tsx
src/useVirtual.ts

- Fix(useVirtual): do not trigger `onScroll` and `loadMore` by internally scroll-to method

Fix(useVirtual): do not trigger `onScroll` and `loadMore` by internally scroll-to method

---

.changeset/forty-cameras-battle.md
src/useVirtual.ts

- Perf(useVirtual): remove unnecessary internal `useDebounce` for reducing bundle size

Perf(useVirtual): remove unnecessary internal `useDebounce` for reducing bundle size

---

.changeset/tall-gifts-fail.md
src/useVirtual.ts

- perf (useVirtual): mutate inner element styles only when items are updated

Perf (useVirtual): mutate inner element styles only when items are updated

---

.changeset/strong-crews-double.md
src/useVirtual.ts

- fix: correct the initial `e.userScroll` of `loadMore` callback from `true` to `false`

Fix: correct the initial `e.userScroll` of `loadMore` callback from `true` to `false`

---

.changeset/happy-dolls-melt.md
src/useVirtual.ts

stickyIndices must be dynamic. A good example of a chat room where the date should always be updated is ( #239 )

stickyIndices can be dynamic

---

.changeset/wild-colts-tie.md
src/useVirtual.ts

Fix: filter data with dynamic size causes empty row/column ( #248 )

Fix: filter data with dynamic size causes empty row/column

---

.changeset/cold-camels-knock.md
src/useVirtual.ts

Fix: app crash when dynamic change data (from short to long) ( #248 )

Fix: app crash when dynamic change data (from short to long)

---

.changeset/nine-tigers-tell.md
README.md
src/__tests__/useVirtual.tsx
src/types/index.ts
src/types/react-cool-virtual.d.ts
src/useVirtual.ts

- Feat: use `startItem` instead `startItemIndex` for pre-pending items (#361)

Feat: use `startItem` instead `startItemIndex` for pre-pending items
